-- Create the games table
create table games (
  id bigint generated by default as identity primary key,
  code text unique not null,
  host text not null,
  player_count integer not null,
  mafia_count integer not null,
  players jsonb not null,
  normal_word text not null,
  mafia_word text not null,
  status text not null,
  created timestamp with time zone not null,
  votes jsonb,
  voting_complete boolean default false,
  mafia_revealed boolean default false
);

-- Enable Row Level Security
alter table games enable row level security;

-- Allow anyone to read games
create policy "Anyone can read games"
  on games for select
  using (true);

-- Allow anyone to insert games
create policy "Anyone can insert games"
  on games for insert
  with check (true);

-- Allow anyone to update games
create policy "Anyone can update games"
  on games for update
  using (true); 